### ISSUE TITLE
async set_position_velocity_ned(position_ned_yaw, velocity_ned_yaw) surprising behavior

### ISSUE THREAD

**Issue by amaalo2** [mavlink/MAVSDK-Python#327] opened 2021-03-26 16:49 UTC
Hello,

I am using the async `set_position_velocity_ned(position_ned_yaw, velocity_ned_yaw)` API for a collision avoidance project where I have two quadrotors (ownship and intruder) meeting at a point. I have a problem with the design of the API and with its implementation.

_Design_
I find it strange that `set_position_velocity_ned(position_ned_yaw, velocity_ned_yaw)` requires both a destination point a velocity vector. This could potentially lead to a contradictory scenario. Consider the following : the ownship is at (0,0,-1)  and wants to go to (0,0,-10). With the final point specified then the direction of the velocity vector is constrained. Hence, only the speed should be fed into the API. Furthermore, a user could give a wrong velocity vector to the API and that should not happen. Here, one could feed in v = (1,0,0) which should not be allowed.

_Implementation error_

Even with the appropriate velocity given to the API, the API ignores the feed-forward velocity command.  I have written below a simple code which reproduces the issue. 

`#!/usr/bin/env python3

"""
Caveat when attempting to run the examples in non-gps environments:

`drone.offboard.stop()` will return a `COMMAND_DENIED` result because it
requires a mode switch to HOLD, something that is currently not supported in a
non-gps environment.
"""

import asyncio

from mavsdk import System
from mavsdk.offboard import (OffboardError, PositionNedYaw, VelocityNedYaw)

async def run():
    """ Does Offboard control using position NED coordinates. """

    drone = System(mavsdk_server_address="localhost", port=50040)
    await drone.connect()

    print("-- Arming")
    await drone.action.arm()

    print("-- Setting initial setpoint")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))

    print("-- Starting offboard")
    try:
        await drone.offboard.start()
    except OffboardError as error:
        print(f"Starting offboard mode failed with error code: {error._result.result}")
        print("-- Disarming")
        await drone.action.disarm()
        return

    async def print_z_velocity(drone):
        async for odom in drone.telemetry.position_velocity_ned():
            print(odom.velocity.down_m_s)

    asyncio.ensure_future(print_z_velocity(drone))

    print("-- Go 0m North, 0m East, -10m Down within local coordinate system")
    await drone.offboard.set_position_velocity_ned(PositionNedYaw(0.0, 0.0, -10.0, 0.0),VelocityNedYaw(0.0,0.0,-1.0,0.0))
    await asyncio.sleep(10)

    await drone.action.land()

    print("-- Stopping offboard")
    try:
        await drone.offboard.stop()
    except OffboardError as error:
        print(f"Stopping offboard mode failed with error code: {error._result.result}")

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
`

Here are the z velocity results where it clear that the quadrotor goes faster than the desired 1m/s. 

0.003411977319046855
-0.02176520600914955
-0.05580098554491997
-0.11217258125543594
-0.2600444555282593
-0.39789730310440063
-0.5122178792953491
-0.660200297832489
-0.7678126096725464
-0.855706512928009
-0.9729937314987183
-1.0613586902618408
-1.1354469060897827
-1.2376779317855835
-1.3175787925720215
-1.3855540752410889
-1.480755090713501
-1.555150032043457
-1.6449717283248901
-1.7020119428634644
-1.758142352104187
-1.8004438877105713
-1.8510819673538208
-1.8849047422409058
-1.9109963178634644
-1.9443066120147705
-1.9682416915893555
-1.986976146697998
-2.0117154121398926
-2.030327081680298
-2.0454864501953125
-2.065434217453003
-2.0806665420532227
-2.09348201751709
-2.1107797622680664
-2.124683141708374
-2.1409847736358643
-2.162337064743042
-2.175767660140991
-2.1867549419403076
-2.200801134109497
-2.2117955684661865
-2.2206413745880127
-2.233596086502075
-2.2434446811676025
-2.2524423599243164
-2.264188528060913
-2.273519515991211
-2.28562068939209
-2.2940683364868164
-2.3069422245025635
-2.3175606727600098
-2.3260397911071777
-2.336127281188965
-2.344203233718872
-2.354729652404785
-2.3630993366241455
-2.3703200817108154
-2.3808751106262207
-2.3897814750671387
-2.3968911170959473
-2.4066781997680664
-2.414121150970459
-2.4209282398223877
-2.430767059326172
-2.4382121562957764
-2.4450669288635254
-2.4543728828430176
-2.4619994163513184
-2.4710776805877686
-2.477555513381958
-2.4847755432128906
-2.4942824840545654
-2.5007166862487793
-2.5081567764282227
-2.5146894454956055
-2.523890733718872
-2.530600070953369
-2.536210060119629
-2.543691396713257
-2.5498034954071045
-2.5549731254577637
-2.56154203414917
-2.5665857791900635
-2.57100510597229
-2.578115463256836
-2.5838096141815186
-2.5918920040130615
-2.6094932556152344
-2.6782641410827637
-2.7657010555267334
-2.8153910636901855
-2.8679397106170654
-2.8958373069763184
-2.913264274597168
-2.9262423515319824
-2.9339852333068848
-2.9407033920288086
-2.9448561668395996
-2.9468350410461426
-2.9477293491363525
-2.947617769241333
-2.9479832649230957
-2.9476237297058105
-2.9472384452819824
-2.947021484375
-2.9463937282562256
-2.946147918701172
-2.9466655254364014
-2.9475178718566895
-2.9482648372650146
-2.946978807449341
-2.9293510913848877
-2.8883602619171143
-2.8374404907226562
-2.783179521560669
-2.713067054748535
-2.645510673522949
-2.5438878536224365
-2.4598100185394287
-2.384570598602295
-2.2773821353912354
-2.192857503890991
-2.119844913482666
-2.01694393157959
-1.9360415935516357
-1.8669179677963257
-1.7692292928695679
-1.6933441162109375
-1.6292378902435303
-1.5411440134048462
-1.4570480585098267
-1.4172173738479614
-1.3399684429168701
-1.2813524007797241
-1.212524175643921
-1.166527509689331
-1.1165364980697632
-1.0738568305969238
-1.0165096521377563
-0.9731007814407349
-0.9217208027839661
-0.8875015377998352
-0.8500401377677917
-0.818359911441803
-0.7757961750030518
-0.7435227632522583
-0.7164947390556335
-0.6793810129165649
-0.6503978967666626
-0.6165661811828613
-0.5936762094497681
-0.562603235244751
-0.5388161540031433
-0.5186731219291687
-0.496757447719574
-0.4785786271095276
-0.4542160630226135
-0.43584051728248596
-0.41353535652160645
-0.39880338311195374
-0.38283684849739075
-0.36426520347595215
-0.35104817152023315
-0.33643487095832825
-0.32432329654693604
-0.3078080415725708
-0.2955690920352936
-0.2805788516998291
-0.2710743248462677
-0.260432422161102

@julianoes

**Comment by julianoes** [comment] 2021-03-29 07:23
Ok, I can reproduce it. Something is definitely off. I'm having a look.

**Comment by julianoes** [comment] 2021-03-29 09:11
@amaalo2 it looks like this is a PX4 problem.

If you want you can try my fix: https://github.com/PX4/PX4-Autopilot/pull/17261

**Comment by amaalo2** [comment] 2021-03-29 15:03
Hi @julianoes , I took a look at the pull request, and it seems to have failed the checks. I am not too familiar with PX4 code, so I can't really help there but many thanks for helping out!

**Comment by julianoes** [comment] 2021-03-30 08:29
@amaalo2 you can already checkout that branch for PX4 and test it if you want.

It is however likely going to take a few days for reviews and fixes, until it's merged into PX4 master.

**Comment by julianoes** [comment] 2021-03-30 09:56
@amaalo2 I was educated that the current behavior is actually correct. It allows to add a feed-forward term to the controller, that's also what the documentation of this method says.

It is not, however, a limit. If you want to limit the velocity you need to either use velocity setpoints only, and close the position loop outside. Or you need to use the velocity control parameters and the maximum speed: https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_XY_VEL_MAX

**Closed** 2021-03-30 09:57 UTC

**Comment by daxaxelrod** [comment] 2021-08-02 01:34
Ah, thanks so much @julianoes! I was hoping to set the velocity limit for each action as sometimes our drone has further to go and we can open up the throttle while still moving towards and positionNED. Seems like the param setting is going to work.

Curious what you think of mavlink message type [MAV_CMD_DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED)
