### ISSUE TITLE
Can not run mavsdk_server

### ISSUE THREAD

**Issue by Rikhsitilla** [mavlink/MAVSDK-Python#376] opened 2021-08-10 12:50 UTC
i am using Ubuntu 18.04 ,  and want to connect SITL  with MAVSDK
Here is my code
```
#!/usr/bin/env python3

import asyncio
from mavsdk import System


async def run():

    drone = System()
    await drone.connect(system_address="udp://:14540")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"Drone discovered!")
            break

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok:
            print("Global position estimate ok")
            break

    print("-- Arming")
    await drone.action.arm()

    print("-- Taking off")
    await drone.action.takeoff()

    await asyncio.sleep(5)

    print("-- Landing")
    await drone.action.land()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```

Here is a error:

This installation does not provide an embedded 'mavsdk_server' binary.
If you installed using pip, this means that 'mavsdk_server' is not distributed
for your platform yet (e.g. arm).

You will need to get and run the 'mavsdk_server' binary manually:

  1. Download 'mavsdk_server' from: https://github.com/mavlink/mavsdk/releases
     or build it from source.

  2. Run it, e.g. on port 50051:
     './mavsdk_server -p 50051'

  3. Set the 'mavsdk_server_address' and port when creating the System:
     'drone = System(mavsdk_server_address='localhost', port=50051)'

I build mavsdk_server from source , but could not run ./mavsdk_server -p 50051  , because could not find file directory
Could you suggest any solution

**Comment by JonasVautherin** [comment] 2021-08-10 18:45
Isn't that a duplicate of #375? :thinking: 

Can you please write all the information in the same issue? I won't answer faster if you duplicate your issues, and actually it does take me more time to handle.

**Closed** 2021-08-11 08:52 UTC
