### ISSUE TITLE
Raspberry Pi : from mavsdk : Illegal Instruction

### ISSUE THREAD

**Issue by TheAsuraSlayer** [mavlink/MAVSDK-Python#345] opened 2021-05-12 04:14 UTC
Im starting off with mavsdk on my raspberry pi connected to a pixhawk via the UART.

the following is the code.

when i run it with   "python3 simple_arm.py"

the terminal shows the output as "Illegal Instruction"

i think ive narrowed down the issue to 
`from mavsdk import System`

P.S : Does mavsdk python work on raspberry Pi model B+ (with arm6)?

```python
import asyncio
from mavsdk import System

async def run():
    print("In run")
    drone =System()
    await drone.connect(system_address="udp://localhost:14550")
    print("Waiting to connect to drone.....")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print("Conected to drone: %s" % state.uuid)
            break

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok:
            print("Global position estimate ok")
            break    
if __name__ == "__main__":
    print("In main loop")
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```

**Comment by julianoes** [comment] 2021-05-12 05:25
@TheAsuraSlayer how did you install mavsdk? Did you do `pip3 install --user mavsdk`?

**Comment by TheAsuraSlayer** [comment] 2021-05-12 05:30
> @TheAsuraSlayer how did you install mavsdk? Did you do `pip3 install --user mavsdk`?

Yeah that's how I did it.
I did an update after that too just to be sure

**Comment by julianoes** [comment] 2021-05-12 05:34
Ok, that's odd. Let me try to reproduce that.

Can you run the file mavsdk_server manually. You should find it by looking for it:

```
find ~ -name mavsdk_server
```

E.g. for me, it's `~/.local/lib/python3.9/site-packages/mavsdk/bin/mavsdk_server`

And then run that manually and copy the output here.

**Comment by TheAsuraSlayer** [comment] 2021-05-12 08:49
![image](https://user-images.githubusercontent.com/6386543/117946529-055fd980-b32d-11eb-9bc4-89496e8e2421.png)


 the above is the result if i run it manually

**Comment by julianoes** [comment] 2021-05-12 09:05
Interesting, so that just works fine.

Can you take a screenshot of when the illegal instruction happens?

**Comment by TheAsuraSlayer** [comment] 2021-05-12 09:07
> Interesting, so that just works fine.
> 
> Can you take a screenshot of when the illegal instruction happens?

![image](https://user-images.githubusercontent.com/6386543/117949249-8b7d1f80-b32f-11eb-9c8c-5d4e4ce44d6e.png)

**Comment by julianoes** [comment] 2021-05-12 09:30
Ok, thank you. I'll try to reproduce it.

**Comment by TheAsuraSlayer** [comment] 2021-05-12 09:33
> Ok, thank you. I'll try to reproduce it.

Thank you. The issue definitely is with accesing(importing the mavsdk library)

`from mavsdk import System`

even a simple `import mavsdk` in an otherwise working script is throwing up the same 'Illegal Instruction' error

**Comment by julianoes** [comment] 2021-05-12 09:40
It works for me:
```
./test.py 
In main loop
In run
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting to connect to drone.....
^CTraceback (most recent call last):
  File "./test.py", line 23, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

Are you sure you don't have another `mavsdk_server` that is used somewhere?

You can look for it:
```
sudo find / -name mavsdk_server
```

**Comment by TheAsuraSlayer** [comment] 2021-05-12 09:48
> It works for me:
> 
> ```
> ./test.py 
> In main loop
> In run
> Waiting for mavsdk_server to be ready...
> Connected to mavsdk_server!
> Waiting to connect to drone.....
> ^CTraceback (most recent call last):
>   File "./test.py", line 23, in <module>
>     loop.run_until_complete(run())
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
>     self.run_forever()
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
>     self._run_once()
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
>     event_list = self._selector.select(timeout)
>   File "/usr/lib/python3.7/selectors.py", line 468, in select
>     fd_event_list = self._selector.poll(timeout, max_ev)
> KeyboardInterrupt
> ```
> 
> That's on:
> 
> ```
> Linux rpi1b-test 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux
> ```
> 
> With:
> 
> ```
> pip3 install --upgrade mavsdk
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Requirement already up-to-date: mavsdk in ./.local/lib/python3.7/site-packages (0.17.0)
> Requirement already satisfied, skipping upgrade: aiogrpc>=1.5 in ./.local/lib/python3.7/site-packages (from mavsdk) (1.8)
> Requirement already satisfied, skipping upgrade: protobuf>=3.13.0 in ./.local/lib/python3.7/site-packages (from mavsdk) (3.13.0)
> Requirement already satisfied, skipping upgrade: grpcio>=1.11.0 in /usr/lib/python3/dist-packages (from mavsdk) (1.16.1)
> Requirement already satisfied, skipping upgrade: setuptools in ./.local/lib/python3.7/site-packages (from protobuf>=3.13.0->mavsdk) (50.3.2)
> Requirement already satisfied, skipping upgrade: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf>
> ```
> 
> Are you sure you don't have another `mavsdk_server` that is used somewhere?
> 
> You can look for it:
> 
> ```
> sudo find / -name mavsdk_server
> ```
> 
> Also, I installed grpcio like this:
> 
> ```
> sudo apt install python3-grpcio
> ```


with regards to  find mavsdk_server this is the output

![image](https://user-images.githubusercontent.com/6386543/117955072-4825af80-b335-11eb-8f84-23f59c84fa32.png)

**Comment by julianoes** [comment] 2021-05-12 10:08
Aha! Might it be that you have installed mavsdk_server previously with root? If so, try to remove the root one:
```
sudo rm /usr/local/lib/python3.7/dist-packages/mavsdk*
```

**Comment by TheAsuraSlayer** [comment] 2021-05-12 10:55
> Aha! Might it be that you have installed mavsdk_server previously with root? If so, try to remove the root one:
> 
> ```
> sudo rm -rf /usr/local/lib/python3.7/dist-packages/mavsdk*
> ```
> 
> Or try with
> `sudo pip3 remove mavsdk`

removed the root mavsdk, but still the same problem

![image](https://user-images.githubusercontent.com/6386543/117963853-807dbb80-b33e-11eb-878d-b8acd41ba8fd.png)

![image](https://user-images.githubusercontent.com/6386543/117963899-955a4f00-b33e-11eb-9003-f39a6d70d4e4.png)

```
print("check 1")
import asyncio
print("check 2")
from mavsdk import System

print("Check 3")

async def run():
    print("In run")
    drone =System(mavsdk_server_address="localhost", port=50051)
    await drone.connect(system_address="udp://localhost:14550")
    print("Waiting to connect to drone.....")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print("Conected to drone: %s" % state.uuid)
            break

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok:
            print("Global position estimate ok")
            break
if __name__ == "__main__":
    print("In main loop")
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())

```

**Comment by julianoes** [comment] 2021-05-12 15:08
Interesting, can you check how grpcio is installed?

**Comment by TheAsuraSlayer** [comment] 2021-05-12 15:50
> Interesting, can you check how grpcio is installed?

I'm actually doing a complete reinstall and checking. Will update once it's done

**Comment by TheAsuraSlayer** [comment] 2021-05-12 18:00
> > Interesting, can you check how grpcio is installed?
> 
> I'm actually doing a complete reinstall and checking. Will update once it's done

Unfortunately even after a completely clean install.... THE SAME RESULT

what does ILLEGAL INSTRUCTION even mean

**Comment by julianoes** [comment] 2021-05-13 09:03
Odd! My assumption is that some binary is not armv6 compatible and contains an "illegal instruction" for that architecture.

**Comment by julianoes** [comment] 2021-05-13 09:04
Can you try to run it in gdb to see when/where it happens?

**Comment by TheAsuraSlayer** [comment] 2021-05-14 17:59
> Can you try to run it in gdb to see when/where it happens?

how do i do that? can you walk me through the steps?

**Comment by julianoes** [comment] 2021-05-17 07:42
Something like this: `gdb --args python3 simple_arm.py` and then you enter `run` and enter.

**Comment by beenjamminnallday** [comment] 2021-05-17 14:12
Hello Julian, 

Me and a friend of mine are having the same issue. The difference with the above inquiry is were using a Pi Zero W. I don't think the HW is the issue as ive used the same Pi to run MAVSDK Python (different SD card). On the PI 4 model B, I am not unable to get this error. 

Thanks for your time. Attached is my output from gdp. 

![image](https://user-images.githubusercontent.com/71512316/118503187-62c2a480-b6f8-11eb-9586-62e992665ec4.png)

**Comment by TheAsuraSlayer** [comment] 2021-05-17 14:17
> Something like this: `gdb --args python3 simple_arm.py` and then you enter `run` and enter.

![image](https://user-images.githubusercontent.com/6386543/118503951-b5c44800-b748-11eb-80ba-ee4e968ba1a7.png)



so its basically the same issue with benjamin too.

**Comment by beenjamminnallday** [comment] 2021-05-17 15:06
When trying a manual build for contributors, I got this.
![image](https://user-images.githubusercontent.com/71512316/118511393-db792f00-b6ff-11eb-8809-a2f4195116d1.png)

**Comment by julianoes** [comment] 2021-05-17 15:12
Oh, the hint is `libcrypto` so this might have something to do with openssl.

**Comment by julianoes** [comment] 2021-05-17 15:14
Check this: https://raspberrypi.stackexchange.com/questions/108985/raspian-buster-lite-grep-fails-with-illegal-instruction

**Comment by TheAsuraSlayer** [comment] 2021-05-28 02:19
> Check this: https://raspberrypi.stackexchange.com/questions/108985/raspian-buster-lite-grep-fails-with-illegal-instruction

tried a different powersupply. reinstalled everything from scratch. still no luck

**Comment by daxaxelrod** [comment] 2021-06-05 21:49
Getting the same thing. I'm able to connect to the vehicle using mavproxy.py

**Comment by daxaxelrod** [comment] 2021-06-05 22:00
Another note, I got illegal instructions when I was running on a Pi zero w 1.1 2017. I switched back to my normal RPi 3 and the error went away. Chipset architecture related maybe?

**Comment by julianoes** [comment] 2021-06-07 06:14
Maybe. I could not see it with my RPi1 which should be the same arch as RPi Zero W. Can you tell me which OS and exactly which version you are using? That way I can try to reproduce it again.

**Comment by liuuuk311** [comment] 2021-06-10 07:57
Hello @julianoes I have the same problem describe above and I'm using this version
```
pi@raspberrypi:~ $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: 6d7ad4a334794ff79b3684014c62b213
           Boot ID: fa5c334e80fe4b5983a95098e9889e39
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.17+
      Architecture: arm
 ```

**Comment by julianoes** [comment] 2021-06-10 08:35
And which steps did you do to install mavsdk and the pip dependencies?

**Comment by liuuuk311** [comment] 2021-06-10 10:28
Initially I tried just `pip3 install mavsdk`. Then the error came up and I tought was because of the mavsdk_server so I downloaded the compiled version from [here](https://github.com/mavlink/MAVSDK/releases). However the error is still present.

By reading all the comments on this issue, it seems like it's not a problem with the mavsdk_server, is it?

**Comment by julianoes** [comment] 2021-06-10 12:59
I'm suspecting one of the libraries used, mostly because it works for me. I'll try fresh to reproduce it.

**Comment by daxaxelrod** [comment] 2021-06-10 19:10
@julianoes Just to follow up

Pi Zero - Raspbian GNU/Linux Version 9
Python v3.9.5

mavsdk version - 0.18.0 
also tried version 0.17.0

**Comment by julianoes** [comment] 2021-06-14 07:43
Ok, I can reproduce the problem on my RPi 1:

> Operating System: Raspbian GNU/Linux 10 (buster)
> Kernel: Linux 5.10.17+
> Architecture: arm

I believe the problem stems from grpcio. When I install grpcio using `sudo apt-get install python3-grpcio` it works. However, when I install it with pip as part of `pip3 install --user mavsdk` it doesn't work and fails with `Illegal Instruction`.

I've followed up in the issues, see:
https://github.com/grpc/grpc/issues/26474
https://github.com/piwheels/packages/issues/217

For now, I suggest this workaround:
```
pip3 uninstall grpcio
sudo apt-get install python3-grpcio
```

**Comment by liuuuk311** [comment] 2021-06-15 16:30
I'll try your workaround, thank you @julianoes!

**Comment by julianoes** [comment] 2021-07-02 14:58
This should be fixed according to https://github.com/piwheels/packages/issues/217#issuecomment-872874116.

**Closed by julianoes** 2021-07-02 14:58 UTC
Labels: question
